import type { Scene } from './infiniteStory'

// Original scenarios set inside public-domain literary worlds, plus an original film world.
// Stories and dialogue are newly written; no copied book, screenplay or film adaptation text.
export const CLASSIC_WORLDS: Record<string, Scene> = {
  gothic_start:{
    id:'gothic_start',title:'第五卷・來自特蘭西瓦尼亞的邀請',world:'德古拉・卡爾法克斯莊園',theme:'gothic',speaker:'旁白',face:'system',
    lines:[
      '【文學世界：Dracula・1897】你從蒸汽火車醒來。車窗外嘅山巒被黑霧籠罩，車廂桌上放住一封寫有你「真名」嘅邀請函。',
      '車長低聲講：「今晚唔會有回頭車。如果你真係要去城堡，最好喺天黑前決定自己究竟係客人，定係獵物。」',
      '【主神任務】活過第三次日落；確認城堡主人嘅秘密。可選任務：改變一名本來注定死亡嘅角色命運。'
    ],choices:[
      {label:'先向車長查問城堡主人',hint:'調查・獲得規則情報',to:'gothic_carriage'},
      {label:'拆開寫住真名嘅邀請函',hint:'理智 -6・身份線索',to:'gothic_letter',effect:{sp:-6,flags:['gothic_true_letter']}},
      {label:'帶住半張車票直接赴約',hint:'風險較高・提前抵達',to:'gothic_castle',effect:{flags:['gothic_early'],hp:-5}}
    ]
  },
  gothic_carriage:{
    id:'gothic_carriage',title:'末班車上的禁忌',world:'德古拉・卡爾法克斯莊園',theme:'gothic',speaker:'年老車長',face:'neighbor',
    lines:[
      '車長見到你張半截地鐵車票，竟然退後半步：「呢張唔屬於呢度。你係從其他故事入嚟嘅？」',
      '佢畀你一枚銀色十字紋章：「城堡主人唔害怕勇敢嘅人，但佢會記住答應過佢嘅承諾。」',
      '隔住窗，你睇見路邊一名戴住黑帽嘅女子，明明列車仲行緊，佢卻一直跟得上。'
    ],choices:[
      {label:'接過銀紋章，承諾唔隨便應允',to:'gothic_castle',effect:{items:['銀色十字紋章'],flags:['gothic_warned'],journal:'車長警告：德古拉會利用承諾束縛旅人。'}},
      {label:'追問女子身份，試圖改變佢嘅命運',to:'gothic_woman',effect:{flags:['gothic_saw_woman']}},
      {label:'拒絕收禮，靠自己行入山霧',to:'gothic_castle',effect:{flags:['gothic_lone']}}
    ]
  },
  gothic_letter:{
    id:'gothic_letter',title:'封蠟內的陌生字跡',world:'德古拉・卡爾法克斯莊園',theme:'gothic',speaker:'旁白',face:'system',
    lines:[
      '邀請函上每個字都喺慢慢滲血。「我知道你失去咗姓名。倘若你願意留下，呢個世界可以畀返一個名你。」',
      '你翻到背面，發現有另一段筆跡：「記住，吸血鬼唔一定係城堡入面唯一冇影嘅東西。」',
      '你終於明白，呢個世界可能知道你喺零號月台失去名字嘅真正原因。'
    ],choices:[
      {label:'燒毀邀請函，拒絕以名字交易',to:'gothic_castle',effect:{flags:['gothic_burn_letter'],journal:'你拒絕了德古拉以姓名作交易的邀請。'}},
      {label:'保留邀請函，當成誘餌',to:'gothic_castle',effect:{items:['染血邀請函'],flags:['gothic_keep_letter']}}
    ]
  },
  gothic_woman:{
    id:'gothic_woman',title:'不會離開月光的女子',world:'德古拉・卡爾法克斯莊園',theme:'gothic',speaker:'艾莉娜',face:'girl',
    lines:[
      '你跳落月台，發現女子冇腳步聲。佢望住遠方城堡：「我已經死過一次。但每當有人打開故事，我就會再死一次。」',
      '「你哋呢種外來者，唔係應該知道結局咩？可唔可以唔好再睇住我死？」',
      '城堡鐘聲敲響。艾莉娜伸出手，掌心有一條正在消失嘅紅線。'
    ],choices:[
      {label:'答應救佢，帶佢一齊去城堡',hint:'羈絆＋線索・危險',to:'gothic_castle',effect:{flags:['gothic_save_elena'],items:['艾莉娜的紅線'],hp:-7,journal:'你答應改變艾莉娜在德古拉世界反覆死亡的命運。'}},
      {label:'要求佢先講出吸血鬼嘅弱點',to:'gothic_castle',effect:{flags:['gothic_knows_sun'],sp:-4,journal:'艾莉娜透露：城堡真正害怕的是清晨第一道光。'}},
      {label:'認為佢可能係陷阱，獨自離開',to:'gothic_castle',effect:{flags:['gothic_avoided_elena']}}
    ]
  },
  gothic_castle:{
    id:'gothic_castle',title:'城堡的第三次日落',world:'德古拉・卡爾法克斯莊園',theme:'gothic',speaker:'德古拉伯爵',face:'clerk',
    lines:[
      '城堡大門喺你身後自動鎖上。伯爵企喺燭光與黑影之間，注視你手腕上嘅主神印記。',
      '「你唔屬於我呢本故事。每次有人改變情節，就會有另一個人承受代價。」',
      '佢攤開一張契約：「只要承認自己係我嘅客人，我會保證你活過三個晚上。」你見到窗邊隱藏住一把通往塔樓嘅舊鑰匙。'
    ],choices:[
      {label:'先假裝接受招待，暗中調查',hint:'安全調查・失去一晚',to:'gothic_library',effect:{flags:['gothic_guest'],sp:-7}},
      {label:'直接拒絕契約，尋找塔樓鑰匙',hint:'生命 -12・速攻路線',to:'gothic_tower',effect:{flags:['gothic_refusal'],hp:-12}},
      {label:'提出交換：用失去嘅名字換艾莉娜自由',hint:'需要救人承諾',to:'gothic_elena_trade',requires:'gothic_save_elena'},
      {label:'展示車長的銀色紋章要求離開',hint:'不戰解謎路線',to:'gothic_tower',requiresItem:'銀色十字紋章',effect:{flags:['gothic_silver_route']}}
    ]
  },
  gothic_library:{
    id:'gothic_library',title:'未出版的最後一頁',world:'德古拉・卡爾法克斯莊園',theme:'gothic',speaker:'旁白',face:'system',
    lines:[
      '深夜，你喺書房見到一冊永遠揭唔完嘅《德古拉》。每翻一頁，入面嘅人物就重複一次已經寫好嘅命運。',
      '最後一頁卻係空白，上面浮現你嘅指紋。你記起主神規則：「完成小說結局，或者改寫小說結局，任務都會認可。」',
      '書櫃後傳出一把細聲：「如果你寫出我生還，伯爵就會發現你。」'
    ],choices:[
      {label:'喺空白頁寫低「艾莉娜活過黎明」',hint:'理智 -13・改寫劇情',to:'gothic_tower',effect:{sp:-13,flags:['gothic_rewrite_elena'],journal:'你在未出版的結尾改寫艾莉娜的命運。'}},
      {label:'偷走空白頁，帶返其他世界',hint:'帶走跨世界道具',to:'gothic_tower',effect:{items:['小說空白尾頁'],flags:['gothic_stolen_page']}},
      {label:'唔干涉原著，靜待第三次日落',hint:'理智 +6',to:'gothic_tower',effect:{sp:6,flags:['gothic_obey_plot']}}
    ]
  },
  gothic_elena_trade:{
    id:'gothic_elena_trade',title:'名字可以交易嗎',world:'德古拉・卡爾法克斯莊園',theme:'gothic',speaker:'德古拉伯爵',face:'clerk',
    lines:[
      '伯爵笑咗：「你居然想用一樣自己已經失去嘅嘢作交易？」佢喺空中打開一份契約，紙上竟然寫住玩家 0000。',
      '「無名之人，只有你可以選擇令其他角色唔再跟住劇本死亡。但代價會落喺你自己身上。」',
      '艾莉娜隔住大門喊你：「唔好為咗我賣咗自己。」'
    ],choices:[
      {label:'用自己嘅理智換取佢存活',hint:'理智 -20；隱藏救贖',to:'gothic_tower',effect:{sp:-20,flags:['gothic_elena_contract'],journal:'你簽下契約，承諾承擔艾莉娜原定的死亡。'}},
      {label:'識破交易漏洞：自己本來就冇名字',hint:'需要零號月台身份',to:'gothic_tower',requires:'no_name',effect:{flags:['gothic_contract_broken'],points:20}},
      {label:'拒絕交易，另尋出路',to:'gothic_library'}
    ]
  },
  gothic_tower:{
    id:'gothic_tower',title:'第三次日落之後',world:'德古拉・卡爾法克斯莊園',theme:'gothic',speaker:'旁白',face:'system',
    lines:[
      '第三次日落來臨。城堡每一道門都開始滲血，伯爵嘅影子順住牆壁爬向塔樓。',
      '你站喺鐘樓頂。東方天際已經有一道極淡嘅白色，距離黎明只差最後幾分鐘。',
      '塔樓有兩道出口：一條通往城外；另一條通向故事根本唔應該存在嘅「第零頁」。'
    ],choices:[
      {label:'打開塔樓窗，等第一道日光穿入',hint:'需要日光情報・較安全',to:'gothic_ending',requires:'gothic_knows_sun',effect:{flags:['gothic_dawn'],journal:'你以清晨第一道光瓦解了吸血鬼的契約。'}},
      {label:'拉住艾莉娜一齊跳過門檻',hint:'需要救人承諾・生命 -10',to:'gothic_ending',requires:'gothic_save_elena',effect:{flags:['gothic_elena_escape'],hp:-10}},
      {label:'踏入不存在的第零頁',hint:'主線真相・理智 -15',to:'gothic_ending',effect:{flags:['gothic_zero_page'],sp:-15,items:['第零頁殘章'],journal:'《德古拉》的第零頁顯示：主神早在故事開始前已替你安排身份。'}},
      {label:'沿樓梯獨自逃離城堡',hint:'安全離開，但無法救人',to:'gothic_ending',effect:{flags:['gothic_escaped_alone']}}
    ]
  },
  gothic_ending:{
    id:'gothic_ending',title:'結算・被改寫的黎明',world:'德古拉・卡爾法克斯莊園',theme:'gothic',speaker:'主神系統',face:'system',
    lines:[
      '黎明降臨之際，城堡像浸喺水裏嘅舊照片一樣褪色。你望住身後，發現小說最后一頁寫住嘅結局，已經唔再固定。',
      '【世界觀測完成】你可以選擇保存故事嘅自由，亦可以帶走主神本來唔想你見到嘅劇本殘章。'
    ],choices:[
      {label:'記錄艾莉娜的新命運，返回中轉站',hint:'救人結局',to:'hub_return',requires:'gothic_elena_escape',effect:{clearWorld:'德古拉',flags:['gothic_saved_end'],points:110,xp:60,journal:'你令德古拉世界原定死亡的艾莉娜逃出生天。'}},
      {label:'帶走第零頁揭示的異常，返回中轉站',hint:'真相結局',to:'hub_return',requires:'gothic_zero_page',effect:{clearWorld:'德古拉',flags:['gothic_truth_end'],points:90,xp:65}},
      {label:'接受結算，帶住經歷離開',hint:'普通通關',to:'hub_return',effect:{clearWorld:'德古拉',flags:['gothic_normal_end'],points:70,xp:45}}
    ]
  },
  arctic_start:{
    id:'arctic_start',title:'第六卷・冰原上的造物者',world:'科學怪人・北境冰原',theme:'arctic',speaker:'旁白',face:'system',
    lines:[
      '【文學世界：Frankenstein・1818】你醒喺冰封嘅船艙。窗外有人拖住一副幾乎冇氣息嘅高大身軀，踩過雪地。',
      '船長遞畀你一本沾咗雪嘅日誌：「有個叫維克多·法蘭肯斯坦嘅人，話佢製造咗自己最恐懼嘅東西。」',
      '【主神任務】判斷怪物係加害者定受害者。你可以照原本嘅悲劇收場，亦可以喺最后一場追逐之前作出介入。'
    ],choices:[
      {label:'去甲板追住嗰道巨大身影',hint:'危險・提前見造物',to:'arctic_creature',effect:{hp:-8}},
      {label:'先讀維克多留低嘅實驗日誌',hint:'調查・世界真相',to:'arctic_diary'},
      {label:'同船長傾偈，確認真正死因',hint:'生存情報',to:'arctic_captain'}
    ]
  },
  arctic_captain:{
    id:'arctic_captain',title:'船長的另一個版本',world:'科學怪人・北境冰原',theme:'arctic',speaker:'沃爾頓船長',face:'neighbor',
    lines:[
      '船長指住遠處：「我哋一直追住法蘭肯斯坦，但我見過嗰位造物。佢救過一個被雪埋住嘅水手。」',
      '「人哋畀佢一個怪物嘅稱呼，就等於證明佢冇心？你唔係都冇自己個名咩？」',
      '船長打開一個鐵盒，裏面有法蘭肯斯坦未用完嘅機械零件。'
    ],choices:[
      {label:'接過零件，嘗試修好供暖裝置',hint:'回復生命 +10',to:'arctic_diary',effect:{hp:10,items:['黃銅齒輪'],flags:['arctic_helped_crew']}},
      {label:'告訴船長你來自故事之外',hint:'理智 -6・取得信任',to:'arctic_creature',effect:{sp:-6,flags:['arctic_confessed']}},
      {label:'拒絕介入，先去搵造物者',to:'arctic_diary'}
    ]
  },
  arctic_diary:{
    id:'arctic_diary',title:'怪物寫下的第一句話',world:'科學怪人・北境冰原',theme:'arctic',speaker:'旁白',face:'system',
    lines:[
      '維克多嘅筆跡越寫越潦草，最後幾頁反覆寫住同一句：「我嘅錯誤唔係創造生命，而係拒絕面對佢。」',
      '日誌夾住一張未寄出嘅信，收件人寫住「我的孩子」，但信封仍然封得好好。',
      '你突然想起阿霧話過：「唔好因為一個人同你唔同，就即刻當佢係敵人。」'
    ],choices:[
      {label:'保存未寄出的信，打算交畀造物',hint:'解鎖和平路線',to:'arctic_creature',effect:{items:['維克多未寄的信'],flags:['arctic_letter'],journal:'維克多認為真正的錯是拋棄自己創造的生命。'}},
      {label:'燒掉日誌，拒絕再重演悲劇',hint:'理智 -8',to:'arctic_confront',effect:{sp:-8,flags:['arctic_burned_diary']}},
      {label:'以「真相視界」尋找被刪去嘅一頁',hint:'需要調查天賦',to:'arctic_memory',requiresTalent:'insight'}
    ]
  },
  arctic_memory:{
    id:'arctic_memory',title:'被刪除的另一個實驗',world:'科學怪人・北境冰原',theme:'arctic',speaker:'系統的低語',face:'system',
    lines:[
      '你用天賦睇穿紙上墨痕，發現一本世界劇本被人篡改：維克多其實曾經打算接納造物，卻被不明力量阻止。',
      '「觀測者想確保悲劇發生。」你喺封面上見到同自己一樣嘅玩家編號 0000。'
    ],choices:[
      {label:'留低證據，阻止系統強制悲劇',to:'arctic_creature',effect:{flags:['arctic_altered_script'],items:['被刪的實驗頁'],sp:-7,xp:35,journal:'科學怪人世界的悲劇被觀測者修改過。'}}
    ]
  },
  arctic_creature:{
    id:'arctic_creature',title:'冰原上的無名者',world:'科學怪人・北境冰原',theme:'arctic',speaker:'造物',face:'clerk',
    lines:[
      '高大嘅造物緩緩轉身，皮膚上有一道道縫線，眼睛卻平靜得出奇。',
      '「你亦冇名字？」佢望住你。「人類唔肯畀我名字，於是任何人都可以話我係怪物。」',
      '佢冇攻擊，只係問你：「如果你可以幫我問我父親一句說話，你會唔會幫？」'
    ],choices:[
      {label:'將維克多未寄的信交畀佢',hint:'羈絆解鎖',to:'arctic_reconciliation',requiresItem:'維克多未寄的信',effect:{flags:['arctic_creature_trust']}},
      {label:'答應替佢找維克多',to:'arctic_confront',effect:{flags:['arctic_promised_help']}},
      {label:'問佢曾經傷害過邊個',hint:'理智 -7・真相',to:'arctic_confront',effect:{sp:-7,flags:['arctic_asked_guilt']}},
      {label:'驚恐後退，通知船長佢喺呢度',hint:'傷害信任',to:'arctic_confront',effect:{flags:['arctic_betrayed_creature']}}
    ]
  },
  arctic_reconciliation:{
    id:'arctic_reconciliation',title:'一封遲到的信',world:'科學怪人・北境冰原',theme:'arctic',speaker:'造物',face:'clerk',
    lines:[
      '造物將信紙放喺手掌中央，讀咗好耐。你發現佢啲手雖然巨大，卻輕得似驚整爛紙。',
      '「原來佢曾經想見我。」佢抬起頭，「帶我去見佢。只係一次都好。」'
    ],choices:[
      {label:'帶住佢返船艙，要求兩個人對話',hint:'和平路線・生命 -6',to:'arctic_confront',effect:{flags:['arctic_reconcile'],hp:-6,journal:'你成功獲得造物信任，令佢願意與維克多對話。'}},
      {label:'勸佢遠走，唔需要再得到承認',to:'arctic_ending',effect:{flags:['arctic_free_creature'],journal:'你勸造物放下被承認的執念，獨自離開冰原。'}}
    ]
  },
  arctic_confront:{
    id:'arctic_confront',title:'兩個互不承認的生命',world:'科學怪人・北境冰原',theme:'arctic',speaker:'維克多',face:'neighbor',
    lines:[
      '你喺船艙搵到虛弱嘅維克多。佢握緊被褥：「你想我面對佢？我一見到佢，就諗起我失去嘅所有人。」',
      '造物企喺門外，冇再向前。窗外嘅暴風雪即將吞沒整艘船。',
      '呢一刻，原本故事應該走向最後嘅遺憾；但你知道，只要開口，就可能改寫兩個人嘅結局。'
    ],choices:[
      {label:'要求維克多承認造物係自己嘅孩子',hint:'需建立信任',to:'arctic_ending',requires:'arctic_reconcile',effect:{flags:['arctic_peace'],sp:-8,journal:'維克多終於承認自己對造物的責任。'}},
      {label:'揭露世界故事曾被系統篡改',hint:'需持有被刪除劇本',to:'arctic_ending',requires:'arctic_altered_script',effect:{flags:['arctic_truth'],items:['觀測者修改記錄'],sp:-10}},
      {label:'將造物留喺冰原，先救船上其他人',hint:'生存抉擇',to:'arctic_ending',effect:{flags:['arctic_saved_crew'],hp:-5}},
      {label:'唔作干預，讓悲劇照既定結局發生',to:'arctic_ending',effect:{flags:['arctic_original_end'],sp:-5}}
    ]
  },
  arctic_ending:{
    id:'arctic_ending',title:'結算・不被承認的名字',world:'科學怪人・北境冰原',theme:'arctic',speaker:'主神系統',face:'system',
    lines:[
      '暴風雪終於停落嚟。一本本記錄生命嘅日誌散落喺甲板，唯獨你原本嘅名字始終冇出現。',
      '【文學世界結算】故事可以重演，但你對造物嘅判斷，已經變成下一個世界會讀到嘅證據。'
    ],choices:[
      {label:'保存和解契約，帶走改寫後嘅故事',hint:'和平結局',to:'hub_return',requires:'arctic_peace',effect:{clearWorld:'科學怪人',flags:['arctic_good_end'],items:['無名者的約定'],points:110,xp:80,journal:'你令維克多與造物有機會和解。'}},
      {label:'公開被觀測者修改的劇本',hint:'主神真相路線',to:'hub_return',requires:'arctic_truth',effect:{clearWorld:'科學怪人',flags:['arctic_truth_end'],points:95,xp:80}},
      {label:'返回中轉站，保留所有未解問題',hint:'普通結局',to:'hub_return',effect:{clearWorld:'科學怪人',flags:['arctic_normal_end'],points:70,xp:50}}
    ]
  },
  cinema_start:{
    id:'cinema_start',title:'第七卷・消失的最後一幕',world:'第十三號放映室',theme:'cinema',speaker:'旁白',face:'system',
    lines:[
      '【電影世界：原創黑白懸疑片《第十三號放映室》】你坐喺一間只得一個觀眾嘅老戲院。銀幕裏面有人正看住你。',
      '電影開始播放：一名女演員要喺午夜被劇中兇手殺死，但場景每次重播，女演員都會望向觀眾席求救。',
      '字幕突然轉成你熟悉嘅廣東話：「你唔係觀眾。你已經入咗鏡頭。」'
    ],choices:[
      {label:'照住原有劇本扮演臨時演員',hint:'低風險・掌握角色關係',to:'cinema_actor',effect:{flags:['cinema_actor_route']}},
      {label:'直接走向銀幕，試圖改變最後一幕',hint:'理智 -10・直接介入',to:'cinema_screen',effect:{sp:-10,flags:['cinema_forced_screen']}},
      {label:'查看放映機背面嘅製作名單',hint:'調查・解鎖幕後真相',to:'cinema_projection'}
    ]
  },
  cinema_actor:{
    id:'cinema_actor',title:'黑白世界內的女主角',world:'第十三號放映室',theme:'cinema',speaker:'黎音',face:'girl',
    lines:[
      '你踏入攝影棚，身上所有顏色都變成黑白。女演員黎音偷偷拉住你：「求你唔好跟住劇本講對白。」',
      '「每個人都知道我下一幕會死，但導演每次都叫我笑住拍多一次。」',
      '你發現攝影機並冇任何攝影師，鏡頭卻一直對住你。'
    ],choices:[
      {label:'答應喺最後一幕救黎音',hint:'信任支線',to:'cinema_set',effect:{flags:['cinema_save_liyin'],items:['黎音的場記板'],journal:'你承諾阻止黑白電影女主角黎音的必死結局。'}},
      {label:'要求先睇真正嘅劇本',to:'cinema_projection',effect:{flags:['cinema_actor_doubt']}},
      {label:'問黎音有冇試過自己逃跑',to:'cinema_set',effect:{flags:['cinema_knows_retake'],sp:-4}}
    ]
  },
  cinema_screen:{
    id:'cinema_screen',title:'銀幕不再需要觀眾',world:'第十三號放映室',theme:'cinema',speaker:'放映室廣播',face:'system',
    lines:[
      '你穿過銀幕，身後戲院變成漆黑一片，身前則係被人造月光照住嘅街道。',
      '一把機械聲音響起：「警告，臨時角色不可修改劇情。」隨即一張舊電影票跌落你手中。',
      '你留意到電影票寫住「第十三次拍攝」，而每次失敗嘅女主角都被迫重新開始。'
    ],choices:[
      {label:'拾起舊戲票，研究重拍次數',to:'cinema_projection',effect:{items:['第十三次拍攝戲票'],flags:['cinema_retake_count']}},
      {label:'沿街尋找黎音',to:'cinema_actor',effect:{hp:-7}},
      {label:'直接破壞片場照明',to:'cinema_set',effect:{flags:['cinema_dark_set'],sp:-7}}
    ]
  },
  cinema_projection:{
    id:'cinema_projection',title:'放映機後的剪接台',world:'第十三號放映室',theme:'cinema',speaker:'旁白',face:'system',
    lines:[
      '放映機上夾住一疊廢棄菲林。你發現每次黎音死亡嘅片段，末尾都會多出幾格你自己嘅背影。',
      '片段嘅日期竟然寫住零號月台第一次出現嗰晚。你開始懷疑：係你闖入呢套電影，定係有人將你剪入去？',
      '剪接台上有兩把剪刀，一把寫住「刪除角色」，另一把寫住「改寫場景」。'
    ],choices:[
      {label:'偷走「改寫場景」剪刀',hint:'道具路線・改變結局',to:'cinema_set',effect:{items:['改寫場景剪刀'],flags:['cinema_edit_tool'],journal:'放映機會利用玩家過去的輪迴片段強制拍攝死亡場景。'}},
      {label:'調查自己出現嘅影片，尋找觀測者',hint:'理智 -12・主線真相',to:'cinema_set',effect:{sp:-12,flags:['cinema_player_footage'],items:['玩家0000的底片']}},
      {label:'將菲林全部燒毀',hint:'隱藏風險',to:'cinema_set',effect:{flags:['cinema_burn_film'],hp:-9}}
    ]
  },
  cinema_set:{
    id:'cinema_set',title:'午夜最後一幕',world:'第十三號放映室',theme:'cinema',speaker:'神秘導演',face:'clerk',
    lines:[
      '攝影棚開始倒數：「三、二、一……」黎音企喺路燈下，黑影正喺佢背後舉起刀。',
      '導演嘅聲音從四面八方傳嚟：「你既然入咗電影，就要為一個角色安排結局。」',
      '你唔夠時間做晒所有事，必須揀一種方式介入。'
    ],choices:[
      {label:'衝上去推開黎音',hint:'需要承諾救人・生命 -16',to:'cinema_ending',requires:'cinema_save_liyin',effect:{hp:-16,flags:['cinema_rescue'],journal:'你以自己的安全換黎音走出原定死亡鏡頭。'}},
      {label:'用剪刀剪掉兇手出場鏡頭',hint:'解謎路線・需改寫道具',to:'cinema_ending',requiresItem:'改寫場景剪刀',effect:{flags:['cinema_edited_killer'],sp:-7}},
      {label:'讓觀測者認出你，強迫佢停止拍攝',hint:'需要玩家底片・理智 -14',to:'cinema_ending',requiresItem:'玩家0000的底片',effect:{sp:-14,flags:['cinema_exposed_director'],journal:'你揭露電影導演是觀測者安排的劇情管理者。'}},
      {label:'選擇自己扮演電影裏面嘅兇手',hint:'黑暗分支・人物關係受損',to:'cinema_ending',effect:{flags:['cinema_played_killer'],bond:-1,points:35}},
      {label:'保持沉默，任由原定結局上演',hint:'普通結局',to:'cinema_ending',effect:{flags:['cinema_did_nothing'],sp:-10}}
    ]
  },
  cinema_ending:{
    id:'cinema_ending',title:'結算・誰在銀幕外拍攝',world:'第十三號放映室',theme:'cinema',speaker:'主神系統',face:'system',
    lines:[
      '放映機突然停咗。你回頭時，發現觀眾席坐滿你曾經喺不同世界遇到過嘅人。',
      '最後一張空白字幕上慢慢浮現一句：「故事已經結束；但演員會記住呢場戲。」',
      '【電影世界結算】你所扮演嘅角色，將成為其他世界認識你嘅其中一種身份。'
    ],choices:[
      {label:'帶黎音一齊離開銀幕',hint:'救人結局',to:'hub_return',requires:'cinema_rescue',effect:{clearWorld:'第十三號放映室',flags:['cinema_good_end'],items:['黎音的謝幕信'],points:115,xp:70}},
      {label:'將修改後嘅菲林交返主神系統',hint:'改寫劇情結局',to:'hub_return',requires:'cinema_edited_killer',effect:{clearWorld:'第十三號放映室',flags:['cinema_rewrite_end'],items:['未上映的最後一幕'],points:100,xp:75}},
      {label:'公開導演真正身份，離開放映室',hint:'真相結局',to:'hub_return',requires:'cinema_exposed_director',effect:{clearWorld:'第十三號放映室',flags:['cinema_truth_end'],points:105,xp:80}},
      {label:'接受結算，回到中轉站',hint:'普通結局',to:'hub_return',effect:{clearWorld:'第十三號放映室',flags:['cinema_normal_end'],points:60,xp:45}}
    ]
  }
}
