import type { Scene } from './infiniteStory'

/** The Storm Riders (1998 FILM ONLY) - no 2009 sequel or later comic arcs. */
export const STORM_WORLD: Record<string, Scene> = {
  fy_arrival:{
    id:'fy_arrival',title:'03・天下會：風雲際會',world:'風雲雄霸天下（1998）',theme:'rift',speaker:'主神系統',face:'system',
    moods:['mystery','resolve','fear'],
    lines:[
      '【進入香港電影《風雲雄霸天下》（1998）】你穿住一身尋常江湖衣衫，企喺天下會山門外。雄霸已經收聶風、步驚雲同秦霜為徒；江湖勢力正擴張。',
      '你知道泥菩薩嘅預言會令雄霸對兩位弟子起殺心；孔慈嘅婚事將成為師兄弟反目嘅導火線，最後聶風、步驚雲會聯手擊敗雄霸。',
      '【主神任務】活過天下會內亂，幫助風、雲化解雄霸殺局。完成 200 積分／80 XP；【支線】拯救孔慈、保住秦霜、取得武林傳承線索。'
    ],
    choices:[
      {label:'跟秦霜入天下會，以客卿身份觀察',hint:'秦霜支線・較安全',to:'fy_qinshuang',effect:{flags:['fy_enter_as_guest']}},
      {label:'尋訪泥菩薩，先查預言真正意思',hint:'預言支線・理智 -6',to:'fy_prophecy',effect:{flags:['fy_seek_prophecy'],sp:-6}},
      {label:'直接同聶風講你知道佢父親嘅事',hint:'需要慎重贏得信任',to:'fy_wind',effect:{flags:['fy_wind_approach']}}
    ]
  },
  fy_qinshuang:{
    id:'fy_qinshuang',title:'秦霜：天下會不是所有人都願意作惡',world:'風雲雄霸天下（1998）',theme:'rift',speaker:'秦霜',face:'neighbor',
    moods:['mystery','resolve','sad'],
    lines:[
      '秦霜打量你一眼：「你唔似練武之人，點解偏偏喺天下會四處問消息？」佢雖然忠於師父，卻並非完全冇疑心。',
      '你見到雄霸心腹文丑丑匆匆從書房出來，手上捏住一張預言紙。秦霜似乎已經懷疑師父隱瞞咗某啲事。',
      '你可以與秦霜建立合作，或者搶先摸清天下會嘅部署。'
    ],
    choices:[
      {label:'向秦霜展示你知道雄霸可能離間弟子',hint:'秦霜信任支線',to:'fy_prophecy',effect:{flags:['fy_qinshuang_ally'],bond:1,journal:'你提醒秦霜雄霸可能利用孔慈婚事離間風雲。'}},
      {label:'幫佢調查文丑丑送去書房嘅密令',hint:'掌握內部線索',to:'fy_prophecy',effect:{flags:['fy_xiongba_orders'],items:['天下會密令抄本'],sp:-8}},
      {label:'暫時按兵不動，觀察聶風同孔慈',hint:'人物線索',to:'fy_kongchi',effect:{flags:['fy_observer']}}
    ]
  },
  fy_prophecy:{
    id:'fy_prophecy',title:'泥菩薩：金鱗之命',world:'風雲雄霸天下（1998）',theme:'rift',speaker:'泥菩薩',face:'clerk',
    moods:['mystery','fear','resolve'],
    lines:[
      '泥菩薩將機關盒輕放喺桌面：「雄霸信命，亦最驚自己嘅命。佢以為收風雲為徒，就能一路登頂。」',
      '你知道另一半預言會令雄霸相信，聶風與步驚雲將帶來佢嘅敗亡；雄霸於是開始用婚事製造裂痕。',
      '老人望住你：「若你將佢下一步先講出嚟，命運可能更加快反噬。你會點做？」'
    ],
    choices:[
      {label:'記低預言，秘密通知聶風同步驚雲',hint:'聯手主線',to:'fy_wind',effect:{flags:['fy_shared_prophecy'],items:['半張命數圖'],sp:-6,journal:'泥菩薩預言令雄霸決意挑撥風雲。'}},
      {label:'先將預言交畀秦霜查核',hint:'需秦霜信任',to:'fy_wind',requires:'fy_qinshuang_ally',effect:{flags:['fy_qin_knows_prophecy'],xp:25}},
      {label:'隱藏後半段預言，避免提早觸怒雄霸',hint:'延後危機、失去情報優勢',to:'fy_kongchi',effect:{flags:['fy_hide_prophecy'],sp:-4}}
    ]
  },
  fy_wind:{
    id:'fy_wind',title:'聶風：溫柔之人亦會被命運利用',world:'風雲雄霸天下（1998）',theme:'rift',speaker:'聶風',face:'clerk',
    moods:['mystery','sad','resolve'],
    lines:[
      '聶風聽你講起凌雲窟同聶人王，原本平和嘅神色微微變化。雪飲刀仲未返到佢手上，但你清楚凌雲窟最終會係重要一站。',
      '佢問：「師父若真係利用我，咁多年養育之情又算乜？」你察覺佢仍然願意給秦霜同師兄一次解釋機會。',
      '你知道婚事即將宣布；保護孔慈未必只需要武功，更需要有人提早講出真相。'
    ],
    choices:[
      {label:'懇請聶風先同孔慈私下講清楚意願',hint:'保護孔慈・解鎖和平路線',to:'fy_kongchi',effect:{flags:['fy_wind_listened','fy_respect_kongchi'],bond:1}},
      {label:'交出泥菩薩預言請聶風提防雄霸',hint:'需預言線索',to:'fy_cloud',requires:'fy_shared_prophecy',effect:{flags:['fy_wind_warned'],sp:-6}},
      {label:'勸聶風先重查凌雲窟父親死因',hint:'支線・雪飲刀線索',to:'fy_cave',effect:{flags:['fy_wind_cave_route']}}
    ]
  },
  fy_kongchi:{
    id:'fy_kongchi',title:'孔慈：婚事不是命令',world:'風雲雄霸天下（1998）',theme:'rift',speaker:'孔慈',face:'girl',
    moods:['sad','fear','resolve'],
    lines:[
      '孔慈獨自坐喺園內，一聽你提起婚事就默默低頭。你知道雄霸會利用佢嫁畀聶風，挑起步驚雲嘅妒意；原電影佢會喺衝突中被雄霸誤殺。',
      '「我唔係只得一個可以畀人安排嘅命。」佢說。「如果我拒絕，聶風同雲師兄會唔會因此互相殘殺？」',
      '你終於要決定係咪直接介入佢嘅人生，或者繼續等故事既定悲劇發生。'
    ],
    choices:[
      {label:'尊重孔慈意願，幫佢準備安全離開婚宴',hint:'救孔慈必要線索之一',to:'fy_cloud',effect:{flags:['fy_kongchi_escape_plan'],items:['孔慈的書信'],sp:-8,journal:'你幫孔慈擬定撤離婚宴的路線，尊重她自己的決定。'}},
      {label:'先通知步驚雲，要求佢唔好強行帶走孔慈',hint:'可降低誤會',to:'fy_cloud',effect:{flags:['fy_warned_cloud'],bond:1}},
      {label:'唔干預孔慈嘅婚事，避免雄霸懷疑',hint:'保住自身安全但失去機會',to:'fy_cloud',effect:{flags:['fy_kongchi_left_alone']}}
    ]
  },
  fy_cloud:{
    id:'fy_cloud',title:'步驚雲：仇恨可以使人失控',world:'風雲雄霸天下（1998）',theme:'rift',speaker:'步驚雲',face:'clerk',
    moods:['anger','mystery','sad'],
    lines:[
      '步驚雲冷眼望住你。「我嘅事，幾時輪到你管？」但當你提起步家莊同雄霸當年嘅行動，佢終於停低。',
      '電影裏面，孔慈死亡會令步驚雲踏上奪取千年冰魄、失臂、換上麒麟臂嘅路線。你可以提前幫佢睇清楚雄霸嘅用意。',
      '佢冷冷說：「如果師父真係殺咗佢，我會親手報仇。」'
    ],
    choices:[
      {label:'交出孔慈嘅書信，勸步驚雲尊重她',hint:'需孔慈信任・救人路線',to:'fy_wedding',requiresItem:'孔慈的書信',effect:{flags:['fy_cloud_restrained'],sp:-7,journal:'你令步驚雲明白孔慈不應被當成復仇或婚事籌碼。'}},
      {label:'公開雄霸操弄風雲命數嘅證據',hint:'需天下會密令',to:'fy_wedding',requiresItem:'天下會密令抄本',effect:{flags:['fy_cloud_saw_orders'],xp:30}},
      {label:'鼓勵步驚雲立即向雄霸攤牌',hint:'高風險・生命 -15',to:'fy_wedding',effect:{flags:['fy_early_war'],hp:-15}},
      {label:'暫時離開，由步驚雲自己處理',hint:'按電影時間線推進',to:'fy_wedding',effect:{flags:['fy_cloud_uncontrolled']}}
    ]
  },
  fy_wedding:{
    id:'fy_wedding',title:'天下會婚宴：悲劇發生前',world:'風雲雄霸天下（1998）',theme:'rift',speaker:'旁白',face:'system',
    moods:['mystery','fear','resolve'],
    lines:[
      '雄霸主持婚宴，文丑丑面上滿係不安。步驚雲望住孔慈，聶風亦察覺氣氛有異；你知道下一步可能令所有人都付出代價。',
      '你喺台邊見到一道通往內院嘅小門。秦霜已經安排人手，但孔慈有冇辦法順利離開，要睇你之前點做。',
      '【關鍵世界線】救孔慈將偏離電影核心悲劇，主神會增加風險，但可以爭取更高支線獎勵。'
    ],
    choices:[
      {label:'帶孔慈經內院通道離開，將婚宴危機拆散',hint:'需提前安排・生命 -18',to:'fy_after_wedding',requires:'fy_kongchi_escape_plan',effect:{flags:['fy_kongchi_saved'],hp:-18,sp:-9,journal:'你改變電影原本孔慈死亡的命運。'}},
      {label:'以書信令步驚雲暫時退讓，爭取聶風時間',hint:'需步驚雲克制',to:'fy_after_wedding',requires:'fy_cloud_restrained',effect:{flags:['fy_cloud_not_blind'],hp:-10}},
      {label:'交畀秦霜安排，公開雄霸離間師兄弟嘅陰謀',hint:'需秦霜了解預言',to:'fy_after_wedding',requires:'fy_qin_knows_prophecy',effect:{flags:['fy_qin_broke_plot'],sp:-12}},
      {label:'躲避雄霸目光，讓婚宴如電影所示失控',hint:'孔慈將失去生還機會',to:'fy_after_wedding',effect:{flags:['fy_canon_kongchi_loss'],sp:-11}}
    ]
  },
  fy_after_wedding:{
    id:'fy_after_wedding',title:'亂局之後：冰魄與麒麟臂',world:'風雲雄霸天下（1998）',theme:'rift',speaker:'秦霜',face:'neighbor',
    moods:['sad','anger','resolve'],
    lines:[
      '婚宴危機打破天下會表面和平。秦霜終於開始懷疑雄霸；步驚雲同聶風被迫面對自己幾十年來最信任嘅人。',
      '你知道電影往後嘅幾個重要事件：步驚雲會為孔慈接觸千年冰魄，在對抗雄霸時失去手臂，之後得到于岳嘅麒麟臂；聶風則會經歷凌雲窟同血菩提。',
      '但喺你嘅世界線，佢哋點樣到達最終聯手，已經唔一定同電影一樣。'
    ],
    choices:[
      {label:'跟聶風入凌雲窟，尋找血菩提同雪飲刀',hint:'聶風／武學線',to:'fy_cave',effect:{flags:['fy_cave_route'],hp:-9}},
      {label:'探望步驚雲，調查絕世好劍與于岳',hint:'步驚雲／義肢線',to:'fy_cloud_arm',effect:{flags:['fy_cloud_arm_route']}},
      {label:'幫秦霜搜集文丑丑留低嘅密令',hint:'政治／離間陰謀線',to:'fy_final_preparation',effect:{flags:['fy_qin_suspects_xiongba'],sp:-8}}
    ]
  },
  fy_cave:{
    id:'fy_cave',title:'凌雲窟：火麒麟之影',world:'風雲雄霸天下（1998）',theme:'rift',speaker:'聶風',face:'clerk',
    moods:['fear','mystery','resolve'],
    lines:[
      '凌雲窟內熱浪逼人，你遠遠見到火麒麟嘅巨影同殘破石壁。聶風緊握拳頭，終於接近父親失蹤嘅地方。',
      '你知道血菩提同雪飲刀係聶風成長嘅重要線索；而你自己冇電影主角般嘅武功，強行搶奪只會送命。',
      '你必須選擇幫佢、偷學部分身法，或者以其他世界裝備求生。'
    ],
    choices:[
      {label:'協助聶風取得血菩提，自己記錄運氣法門',hint:'武學傳承・不奪主角機緣',to:'fy_final_preparation',effect:{flags:['fy_wind_bodhi_help'],items:['風神腿運氣筆記'],mastery:'martial',hp:-12,xp:30}},
      {label:'用跨世界改良銀弩分散火麒麟注意',hint:'需第二世界裝備',to:'fy_final_preparation',requiresItem:'便攜銀弩',effect:{flags:['fy_crossworld_save'],hp:-8,xp:25}},
      {label:'退後幫聶風守住洞口，不冒險奪物',hint:'穩健生存',to:'fy_final_preparation',effect:{flags:['fy_cave_support'],sp:-7}}
    ]
  },
  fy_cloud_arm:{
    id:'fy_cloud_arm',title:'步驚雲：絕世好劍並非你的獎勵',world:'風雲雄霸天下（1998）',theme:'rift',speaker:'于岳',face:'neighbor',
    moods:['sad','mystery','resolve'],
    lines:[
      '于岳望住你同受傷嘅步驚雲，談起自己一直難以控制嘅麒麟臂。楚楚喺旁照顧傷者，卻唔肯讓任何人將步驚雲當作一把武器。',
      '你知道絕世好劍同麒麟臂都關乎步驚雲後續命運，但你唔應該因為係玩家就自動搶走佢哋。',
      '于岳問你：「如果救一個人，意味住你攞唔到自己想要嘅力量，你仲救唔救？」'
    ],
    choices:[
      {label:'協助楚楚照護步驚雲，學習內息穩定法',hint:'武學路線・維持電影主角傳承',to:'fy_final_preparation',effect:{flags:['fy_cloud_recovered'],items:['麒麟氣息紀錄'],mastery:'martial',sp:-7,xp:30}},
      {label:'嘗試偷取一小塊鍛造用特殊礦材',hint:'得道具但傷害信任',to:'fy_final_preparation',effect:{flags:['fy_took_ore'],items:['鍛劍礦屑'],bond:-1,hp:-8}},
      {label:'尊重于岳決定，只帶走護送消息',hint:'仁義路線',to:'fy_final_preparation',effect:{flags:['fy_yuyue_trust'],xp:15}}
    ]
  },
  fy_final_preparation:{
    id:'fy_final_preparation',title:'雄霸最後一局：風雲要不要聯手',world:'風雲雄霸天下（1998）',theme:'rift',speaker:'文丑丑',face:'neighbor',
    moods:['fear','mystery','resolve'],
    lines:[
      '文丑丑匆忙跑來，說雄霸已經準備同劍聖了結恩怨；風與雲如果彼此不信任，就可能被雄霸逐個擊破。',
      '你從江湖傳聞確認：聶風與步驚雲嘅絕技需要互相配合，唔係一個外來者可以簡單取代。你最大嘅價值係帶住之前調查得到嘅真相。',
      '最後一戰就喺眼前。你選擇證據、信任，定係直接犧牲自己爭取時間？'
    ],
    choices:[
      {label:'用婚事證據同預言說服聶風步驚雲互信',hint:'需先揭露雄霸安排',to:'fy_climax',requires:'fy_cloud_saw_orders',effect:{flags:['fy_wind_cloud_united'],sp:-10}},
      {label:'由秦霜出面證明雄霸原本嘅殺局',hint:'需秦霜已知真相',to:'fy_climax',requires:'fy_qin_knows_prophecy',effect:{flags:['fy_qin_aids_final'],sp:-9}},
      {label:'借助你保護孔慈嘅結果請風雲停手聆聽',hint:'需孔慈存活',to:'fy_climax',requires:'fy_kongchi_saved',effect:{flags:['fy_wind_cloud_united'],bond:1}},
      {label:'自己去擋住天下會伏兵，爭取風雲對話',hint:'生命 -20・無條件可行',to:'fy_climax',effect:{flags:['fy_self_sacrifice'],hp:-20}},
      {label:'放棄介入，按照電影原本路線等風雲聯手',hint:'基本結局',to:'fy_climax',effect:{flags:['fy_follow_canon'],sp:-10}}
    ]
  },
  fy_climax:{
    id:'fy_climax',title:'劍塚：天下之勢',world:'風雲雄霸天下（1998）',theme:'rift',speaker:'聶風',face:'clerk',
    moods:['anger','resolve','joy'],
    lines:[
      '劍塚上狂風翻湧。雄霸已經展開最後攻勢，聶風同帶住麒麟臂嘅步驚雲先後迎上。遠處劍聖嘅挑戰亦令雄霸無法再保持穩妥布局。',
      '你唔係風，亦唔係雲。但你之前有冇保存孔慈、爭取秦霜、讓兩位主角重新信任對方，會決定呢一場結局需要付出幾大代價。',
      '【決定性分支】風雲可以照電影結局擊敗雄霸；亦可以令一部分原本注定發生嘅傷亡消失。'
    ],
    choices:[
      {label:'以已建立嘅互信促成風雲合擊',hint:'救人真結局條件',to:'fy_ending',requires:'fy_wind_cloud_united',effect:{flags:['fy_joint_victory'],hp:-8,xp:35}},
      {label:'安排秦霜保護傷者，阻止雄霸再操控局面',hint:'需秦霜加入',to:'fy_ending',requires:'fy_qin_aids_final',effect:{flags:['fy_qin_survived','fy_xiongba_defeated'],hp:-9}},
      {label:'用從凌雲窟學到嘅步法引開一輪攻勢',hint:'跨關身法',to:'fy_ending',requiresItem:'風神腿運氣筆記',effect:{flags:['fy_martial_help','fy_xiongba_defeated'],hp:-15}},
      {label:'照住電影結局讓風雲擊敗雄霸',hint:'保持原有世界線',to:'fy_ending',effect:{flags:['fy_xiongba_defeated'],sp:-10}}
    ]
  },
  fy_ending:{
    id:'fy_ending',title:'第三世界結算：風雲終局',world:'風雲雄霸天下（1998）',theme:'rift',speaker:'主神系統',face:'system',
    moods:['mystery','resolve','joy'],
    lines:[
      '天下會嘅旗幟慢慢落下。雄霸敗局已定，江湖不再由佢一人決定。聶風、步驚雲、秦霜同孔慈，各自因你嘅選擇走上咗唔同道路。',
      '原電影中曾經無法挽回嘅誤會，而家可能得到修補；但你如果冇及時行動，故事亦會照悲劇原路走落去。',
      '【世界通關】基本 200 積分、80 XP。完成救人與跨世界介入可獲追加支線憑證。'
    ],
    choices:[
      {label:'改命結局：孔慈生還、風雲攜手',hint:'需救孔慈並促成風雲合擊',to:'fy_clear',requiresAll:['fy_kongchi_saved','fy_joint_victory'],effect:{points:130,branch:'C',flags:['fy_kongchi_good_end'],items:['孔慈的平安書信'],journal:'你改變了1998電影孔慈原定的死亡命運。'}},
      {label:'義氣結局：秦霜保護同門',hint:'秦霜路線獎勵',to:'fy_clear',requires:'fy_qin_survived',effect:{points:85,branch:'D',flags:['fy_qin_good_end'],items:['天下會密令卷']} },
      {label:'武學結局：帶走親手記錄嘅身法心得',hint:'跨世界武學成長',to:'fy_clear',requires:'fy_wind_bodhi_help',effect:{points:60,flags:['fy_martial_end'],mastery:'martial'}},
      {label:'領取主線通關結算',hint:'無額外支線要求',to:'fy_clear',effect:{flags:['fy_normal_end']}}
    ]
  },
  fy_clear:{
    id:'fy_clear',title:'三部曲完成：主神召回',world:'風雲雄霸天下（1998）',theme:'rift',speaker:'主神系統',face:'system',
    moods:['resolve','mystery'],
    lines:[
      '你攜帶最後一段電影記憶回到主神空間。銀色獵魔證章、蜂巢紀錄，同當日天下會嘅信箋，一齊喺背包內微微發光。',
      '【三世界成長】科技、秘術、武學三種世界經歷可以並存。主神宣布：新世界傳送權限正在開放；你並唔需要成為電影主角先可以繼續生存。'
    ],
    choices:[{label:'領取第三世界獎勵與三部曲結算',to:'movie_trilogy_epilogue',effect:{clearWorld:'風雲1998',points:200,xp:80,items:['天下會客卿令牌'],mastery:'martial',journal:'電影世界 03《風雲雄霸天下》（1998）通關。已完成首三個輪迴世界。'}}]
  },
  movie_trilogy_epilogue:{
    id:'movie_trilogy_epilogue',title:'輪迴序列結算：下一次進入哪個世界？',world:'主神中轉站',theme:'nexus',speaker:'阿霧',face:'guide',
    moods:['joy','mystery','resolve'],
    lines:[
      '阿霧望住你手上三道不同世界嘅印記。「原本主神只想你完成任務，但你一路上做嘅選擇，已經令嗰啲電影入面嘅人有咗另一種人生。」',
      '【序列結算】《生化危機》→《Van Helsing》→《風雲雄霸天下》已完成。科技、秘術、武學心得與支線憑證會留喺角色身上。',
      '一道從未見過嘅新傳送門出現。但下一套電影係咩，依然由你之後決定。'
    ],
    choices:[
      {label:'檢視新世界與過往電影紀錄',to:'movie_portals'},
      {label:'向阿霧分享三個世界帶回嚟嘅故事',to:'hub_return',effect:{bond:1,flags:['trilogy_recap'],journal:'你與阿霧回顧了前三個電影世界，決定繼續作出自己的抉擇。'}},
      {label:'前往主神商店整理成長成果',action:'shop'}
    ]
  }
}
