import type { Scene } from './infiniteStory'
// Three original film / television / anime-style worlds.
// Each route has consequences, branching NPC loyalties, and persistent rewards.
export const SCREEN_WORLDS:Record<string,Scene>={
 screen_hub:{id:'screen_hub',title:'光幕世界選擇',world:'主神中轉站',theme:'nexus',speaker:'主神系統',face:'system',
  lines:['【世界選擇：電影・劇集・動漫】三塊光幕同時亮起，播放住本來已經寫好嘅故事。','主神低語：「你可以加入原本嘅主角團、拯救注定死亡嘅配角，甚至令反派獲得第二次機會。但每次改寫都要付代價。」','阿霧提醒你：「知道劇情，唔代表你可以控制人心。」'],
  choices:[
   {label:'電影｜深海零號艙',hint:'科幻災難：限時逃生與背叛',to:'film_sub_arrival',notCleared:'深海零號艙'},
   {label:'劇集｜倒數七日',hint:'懸疑劇：每一集揭開另一層真相',to:'tv_week_arrival',notCleared:'倒數七日'},
   {label:'動漫｜逆時學園',hint:'超自然：改變主角原定死亡結局',to:'anime_school_arrival',notCleared:'逆時學園'},
   {label:'其他電影副本',hint:'黑白電影・片場生還',to:'screen_cinema_archives'},
   {label:'舊世界檔案',hint:'保留你之前進入過嘅世界',to:'screen_old_archives'},
   {label:'返回候車廳',to:'hub_return'}
  ]},
 screen_cinema_archives:{id:'screen_cinema_archives',title:'其他電影世界',world:'主神中轉站',theme:'cinema',speaker:'阿霧',face:'guide',
  lines:['「呢兩卷菲林係早期世界檔案。你可以保留劇情以外嘅記憶進入佢哋。」','放映機旁邊寫住一行細字：「玩家改寫劇本，角色不一定接受。」'],
  choices:[{label:'第十三號放映室',to:'cinema_start',notCleared:'第十三號放映室'},{label:'沒有片尾的電影',to:'film_arrival',notCleared:'午夜放映廳'},{label:'返回世界選擇',to:'screen_hub'}]},
 screen_old_archives:{id:'screen_old_archives',title:'被保留的舊世界',world:'主神中轉站',theme:'nexus',speaker:'主神系統',face:'system',
  lines:['【存檔兼容】所有先前劇情與選擇都保留。舊世界可以繼續探索，但不再係主線優先內容。'],
  choices:[{label:'失物管理處',to:'lost_arrival',notCleared:'失物管理處'},{label:'血月公寓',to:'blood_arrival',notCleared:'血月公寓'},{label:'鏡城病院',to:'hospital_arrival',notCleared:'鏡城病院'},{label:'經典小說檔案',to:'screen_literature'} ,{label:'返回世界選擇',to:'screen_hub'}]},
 screen_literature:{id:'screen_literature',title:'非主線小說檔案',world:'主神中轉站',theme:'gothic',speaker:'主神系統',face:'system',
  lines:['呢啲係早期世界紀錄，唔影響之後以電影、劇集、動漫為主嘅方向。'],
  choices:[{label:'德古拉',to:'gothic_start',notCleared:'德古拉'},{label:'科學怪人',to:'arctic_start',notCleared:'科學怪人'},{label:'霧中第七章',to:'novel_arrival',notCleared:'霧中第七章'},{label:'返回世界選擇',to:'screen_hub'}]},
 film_sub_arrival:{id:'film_sub_arrival',title:'電影：深海零號艙',world:'深海零號艙',theme:'cinema',speaker:'旁白',face:'system',
  lines:['【電影副本｜深海零號艙】三千米海底，緊急燈紅光閃爍。你代替咗電影開場十分鐘就會死亡嘅無名工程師。','牆上顯示尚餘 48 分鐘氧氣。唯一生還者原本係女研究員林澄，但你發現佢可能唔係電影中所講嘅人。','林澄推開艙門：「你醒咗？快啲幫我修好逃生艙！」'],
  choices:[{label:'坦白自己知道電影部分結局',hint:'林澄關係＋1',to:'film_sub_investigate',effect:{flags:['sub_told_lin'],bond:1}},{label:'檢查逃生艙爆破痕跡',hint:'調查線索・理智 -5',to:'film_sub_investigate',effect:{sp:-5,flags:['sub_examined']}},{label:'以工程師身份要求獨自操作',hint:'保持秘密',to:'film_sub_decision',effect:{flags:['sub_secret']}}]},
 film_sub_investigate:{id:'film_sub_investigate',title:'消失的鏡頭',world:'深海零號艙',theme:'cinema',speaker:'林澄',face:'girl',moods:['mystery','fear','resolve'],
  lines:['林澄聽完你描述嘅結局，面色蒼白：「電影？唔好再講笑，依家仲有四個人困喺下層！」','你發現逃生艙線路被人刻意剪斷，金屬線上有一塊藍色衣料，與船長制服嘅袖口完全一樣。','林澄盯住你：「你究竟信我，定係信嗰條寫死咗嘅劇情？」'],
  choices:[{label:'信任林澄，一齊救出下層人員',hint:'生命 -14・可能改寫全員命運',to:'film_sub_decision',effect:{hp:-14,flags:['sub_trust_lin','sub_rescue_team'],journal:'你救出本應死於第一幕的研究員。'}},{label:'將證據收好，準備揭穿船長',hint:'解謎路線',to:'film_sub_decision',effect:{flags:['sub_evidence'],items:['破損的藍色布料']}},{label:'要求林澄先交出逃生艙權限',hint:'人物互信受損',to:'film_sub_decision',effect:{flags:['sub_distrust']}}]},
 film_sub_decision:{id:'film_sub_decision',title:'最後十分鐘',world:'深海零號艙',theme:'cinema',speaker:'旁白',face:'system',
  lines:['艙內忽然傳來轟鳴。廣播說：「電影原定生還人數：一。」一隻未知機械手開始強行鎖閉所有出口。','船長指住林澄，堅持要將佢獨自送入逃生艙，但你發現自己有機會推翻所有人都只能死嘅規則。'],
  choices:[{label:'利用藍色布料證明船長係破壞者',hint:'無需犧牲同伴',to:'film_sub_end',requires:'sub_evidence',effect:{flags:['sub_exposed_captain'],xp:20}},{label:'相信林澄，打開全部逃生艙',hint:'需要同伴信任・生命 -9',to:'film_sub_end',requires:'sub_trust_lin',effect:{flags:['sub_crew_survived'],hp:-9}},{label:'自己留低，換取其他人逃生',hint:'高風險・生命 -27',to:'film_sub_end',effect:{flags:['sub_self_sacrifice'],hp:-27}},{label:'按照電影原結局只保住林澄',hint:'容易通關但犧牲他人',to:'film_sub_end',effect:{flags:['sub_original_ending'],sp:-12}}]},
 film_sub_end:{id:'film_sub_end',title:'尾聲：重寫的生還名單',world:'深海零號艙',theme:'cinema',speaker:'主神系統',face:'system',
  lines:['逃生艙衝破海面，天光令你短暫睜唔開眼。螢幕彈出原本電影嘅片尾字幕，但生還名單開始出現改動。','【世界結算】下次見到林澄，佢會記得你嘅抉擇，而唔係只記住劇本。'],
  choices:[{label:'帶走船長破壞證據',to:'hub_return',requires:'sub_exposed_captain',effect:{clearWorld:'深海零號艙',points:115,xp:80,items:['船長罪證'],flags:['sub_truth_end']}},{label:'帶住研究員嘅感謝返回',to:'hub_return',requires:'sub_crew_survived',effect:{clearWorld:'深海零號艙',points:120,xp:80,items:['林澄的聯絡器'],flags:['sub_rescue_end']}},{label:'領取通關獎勵返回主神空間',to:'hub_return',effect:{clearWorld:'深海零號艙',points:60,xp:50,flags:['sub_normal_end']}}]},

 tv_week_arrival:{id:'tv_week_arrival',title:'劇集：倒數七日',world:'倒數七日',theme:'apartment',speaker:'旁白',face:'system',
  lines:['【劇集副本｜第一集】你搬入一幢舊式住宅。電視新聞正播出七日後整棟樓住戶將死亡嘅預告。','新聞畫面忽然轉到你。你發現自己只係第一集無名嘅配角，而真正主角係調查記者葉晴。','門外有人敲三下。從貓眼望出去，一個女人攞住一張死亡名單，正等緊你開門。'],
  choices:[{label:'開門，向葉晴公開自己知未來',to:'tv_week_probe',effect:{flags:['tv_trust_reporter']}},{label:'先調查死亡名單有冇自己',to:'tv_week_probe',effect:{flags:['tv_investigate'],sp:-5}},{label:'將大門鎖實，偷睇下集預告',to:'tv_week_finale',effect:{flags:['tv_skipped_people'],sp:-8}}]},
 tv_week_probe:{id:'tv_week_probe',title:'第四集：被剪走的記憶',world:'倒數七日',theme:'apartment',speaker:'葉晴',face:'girl',moods:['fear','mystery','resolve'],
  lines:['葉晴將名單攤開：「每一日凌晨四點四十四分，所有住客都會唔記得昨日發生過咩。」','你喺監控錄影見到被剪走咗嘅一分鐘，入面有人攞住印住零號月台嘅攝影機。','葉晴問：「如果有一日我都忘記你，你仲會救我哋嗎？」'],
  choices:[{label:'答應幫葉晴公開監控真相',to:'tv_week_finale',effect:{flags:['tv_saved_evidence','tv_reporter_ally'],items:['04:44監控原片']}},{label:'先調查可能係兇手嘅 704 住客',to:'tv_week_finale',effect:{flags:['tv_suspect_innocent'],sp:-6}},{label:'唔想冒險，提前離開呢幢樓',to:'tv_week_finale',effect:{flags:['tv_abandoned_building'],hp:-6}}]},
 tv_week_finale:{id:'tv_week_finale',title:'季終：直播中的第八人',world:'倒數七日',theme:'apartment',speaker:'葉晴',face:'girl',moods:['fear','anger','joy'],
  lines:['第七日，整棟大樓停電。電視卻亮住，主播宣布：「所有住戶將按照原定結局死亡。」','葉晴透過緊急廣播問你：「我應該用原片揭露真相，定係先救最弱嗰個小朋友？」','你意識到，呢個選擇會影響下一季：葉晴會信你、怕你，定係完全唔記得你。'],
  choices:[{label:'公開監控，召集所有人對抗劇本',to:'tv_week_end',requires:'tv_saved_evidence',effect:{flags:['tv_group_survive'],sp:-10}},{label:'相信葉晴決定，自己負責救人',to:'tv_week_end',requires:'tv_reporter_ally',effect:{flags:['tv_reporter_bond'],hp:-12,bond:1}},{label:'獨自帶走錄影，讓事故照原樣發生',to:'tv_week_end',effect:{flags:['tv_solo'],sp:-12}}]},
 tv_week_end:{id:'tv_week_end',title:'季終：還沒拍完的第八集',world:'倒數七日',theme:'apartment',speaker:'主神系統',face:'system',
  lines:['午夜過後，死亡名單上突然多咗一句：「本季未完。」你聽到葉晴嘅聲音從電視另一端傳來。','【劇集世界通關】你選擇救邊個，令呢齣劇擁有唔同嘅第二季。'],
  choices:[{label:'保存全棟住戶的證詞',to:'hub_return',requires:'tv_group_survive',effect:{clearWorld:'倒數七日',points:120,xp:80,flags:['tv_good_end'],items:['七日生還者證詞']}},{label:'收下葉晴送嘅記者證',to:'hub_return',requires:'tv_reporter_bond',effect:{clearWorld:'倒數七日',points:105,xp:75,flags:['tv_ally_end'],items:['葉晴的記者證']}},{label:'接受結算，返回中轉站',to:'hub_return',effect:{clearWorld:'倒數七日',points:65,xp:45,flags:['tv_normal_end']}}]},

 anime_school_arrival:{id:'anime_school_arrival',title:'動漫：逆時學園',world:'逆時學園',theme:'hospital',speaker:'旁白',face:'system',
  lines:['【動漫副本｜第一話】你喺高中教室醒來。窗外天空巨大嘅時鐘正倒轉，每次下課鐘響，都會有一個學生消失。','你記得原本故事：女主角星野澪第十二話會為咗保護全校犧牲，但你原本只係第四話死去嘅無名配角。','澪行到你身旁，帶住戒備問：「你係邊個班？我點解從來冇見過你？」'],
  choices:[{label:'向星野澪坦白穿越身份',to:'anime_school_friend',effect:{flags:['anime_told_truth']}},{label:'假扮轉校生，先觀察同學關係',to:'anime_school_archive',effect:{flags:['anime_undercover']}},{label:'直接阻止第四話將會發生嘅意外',to:'anime_school_friend',effect:{flags:['anime_changed_fourth'],hp:-12}}]},
 anime_school_archive:{id:'anime_school_archive',title:'第二話：不存在的班級名單',world:'逆時學園',theme:'hospital',speaker:'旁白',face:'system',
  lines:['你翻開班級名單，發現被消失嘅學生唔係死亡，而係被移到故事外面。','名單最後一欄寫住你嘅編號「0000」，旁邊加咗一句：「世界線保護失敗時，所有人會返到第一話。」'],
  choices:[{label:'將名單交畀澪，要求合作',to:'anime_school_friend',effect:{flags:['anime_shared_records'],items:['逆時班級名單']}},{label:'收好名單，自己調查逆轉方法',to:'anime_school_friend',effect:{flags:['anime_kept_records'],sp:-7}}]},
 anime_school_friend:{id:'anime_school_friend',title:'第六話：主角不是必須死',world:'逆時學園',theme:'hospital',speaker:'星野澪',face:'girl',moods:['mystery','sad','joy'],
  lines:['星野澪睇住你手腕上嘅印記：「你真係唔係我哋學校嘅人。」佢輕聲問：「如果你知道我最後一定會死，會唔會仍然同我做朋友？」','你知道原本劇情中，澪每次都獨自承擔停止時間倒流嘅代價。','佢笑咗笑：「我唔需要你保護我；我只想你畀我自己決定一次。」'],
  choices:[{label:'尊重澪嘅選擇，畀佢自己決定',to:'anime_school_clock',effect:{flags:['anime_respected_mio'],bond:1}},{label:'堅持改寫原本嘅犧牲劇情',to:'anime_school_clock',effect:{flags:['anime_will_rewrite'],sp:-8}},{label:'同澪尋找其他人可分擔時間代價嘅方法',to:'anime_school_clock',requires:'anime_shared_records',effect:{flags:['anime_share_cost'],xp:30}}]},
 anime_school_clock:{id:'anime_school_clock',title:'第十二話：停止的天空',world:'逆時學園',theme:'hospital',speaker:'星野澪',face:'girl',moods:['fear','resolve','joy'],
  lines:['學園上空嘅時鐘開始碎裂。澪走上鐘樓，向你伸手：「最後一秒，係你幫我決定，定係畀我自己揀？」','你可以照住原劇情犧牲澪、打破犧牲規則，或者讓所有學生一齊承受時間倒流嘅代價。'],
  choices:[{label:'同澪合作分擔時間代價',to:'anime_school_end',requires:'anime_share_cost',effect:{flags:['anime_all_survive'],hp:-18,sp:-10}},{label:'相信澪，尊重佢重新設計嘅選擇',to:'anime_school_end',requires:'anime_respected_mio',effect:{flags:['anime_mio_freedom'],sp:-14}},{label:'獨自承受原本屬於澪嘅犧牲',to:'anime_school_end',effect:{flags:['anime_self_cost'],hp:-25}},{label:'讓時間照原劇情倒流',to:'anime_school_end',effect:{flags:['anime_original'],sp:-15}}]},
 anime_school_end:{id:'anime_school_end',title:'最終話：新的第一天',world:'逆時學園',theme:'hospital',speaker:'主神系統',face:'system',
  lines:['碎裂嘅校鐘重新響起。你從窗戶望出去，終於見到冇寫住倒數數字嘅天空。','【動漫世界結算】故事原本嘅女主角，依家可以按照你哋共同作出嘅選擇繼續活落去。'],
  choices:[{label:'帶走所有同學嘅祝福',to:'hub_return',requires:'anime_all_survive',effect:{clearWorld:'逆時學園',points:125,xp:95,flags:['anime_good_end'],items:['逆時徽章']}},{label:'留下澪嘅未來信件',to:'hub_return',requires:'anime_mio_freedom',effect:{clearWorld:'逆時學園',points:105,xp:80,flags:['anime_mio_end'],items:['星野澪的未來信']}},{label:'領取獎勵返回中轉站',to:'hub_return',effect:{clearWorld:'逆時學園',points:65,xp:50,flags:['anime_normal_end']}}]}
}
