import type { Scene } from './infiniteStory'

// Original scripted worlds inspired by the STRUCTURE of cinematic horror and literary fiction.
// These are original settings and characters, not reproductions of a copyrighted movie or novel.
export const STORY_WORLDS: Record<string, Scene> = {
  film_arrival: {
    id:'film_arrival', world:'午夜放映廳', theme:'rift',title:'電影世界・最後一場戲',speaker:'旁白',face:'system',
    lines:[
      '【電影世界｜《沒有片尾的電影》】雨下得好大。你睜開眼，發現自己坐喺一間空無一人嘅舊戲院。銀幕上嘅人，竟然同你一模一樣。',
      '放映機突然停咗。紅色字幕寫住：「演員必須完成第三次拍攝，否則將永遠留喺影片內。」',
      '最後一排傳出少女低聲啜泣。一個戴白手套嘅放映員企喺側門，手上夾住一本被撕爛嘅劇本。',
      '【主神任務】搵出被剪走嘅最後一格畫面，喺第三次開拍之前阻止電影完結。'
    ],
    choices:[
      {label:'翻查被撕爛嘅劇本',hint:'推理・找出影片規則',to:'film_script'},
      {label:'走向哭泣嘅少女',hint:'人物關係・隱藏結局',to:'film_actress'},
      {label:'向放映員詢問最後一格',hint:'情報・有風險',to:'film_projectionist'}
    ]
  },
  film_script:{
    id:'film_script',world:'午夜放映廳',theme:'rift',title:'第三次開拍的規則',speaker:'旁白',face:'system',
    lines:[
      '劇本第一頁寫住：「第一場，所有人都要笑；第二場，演員必須照著台詞去死；第三場，任何臨時加進劇本嘅人，都會代替原定犧牲者。」',
      '你翻到最後一頁，發現有句話被剪走：「只要有人喺熄燈之前……」',
      '劇本背面寫住放映機故障編號 0000。你突然懷疑，呢套電影可能唔係第一次拍你嘅故事。'
    ],
    choices:[
      {label:'抄低三條規則，同少女對質',to:'film_actress',effect:{flags:['film_script_read'],items:['破損的電影劇本'],journal:'電影規則：第三場會用臨時演員代替原定犧牲者。'}},
      {label:'攞住劇本去搵放映員',to:'film_projectionist',effect:{flags:['film_script_read'],items:['破損的電影劇本']}},
      {label:'當場燒咗劇本，拒絕照拍',hint:'理智 -12・可能引發重拍',to:'film_bad_take',effect:{sp:-12,flags:['film_burned_script']}}
    ]
  },
  film_actress:{
    id:'film_actress',world:'午夜放映廳',theme:'rift',title:'被刪掉名字的女主角',speaker:'黎夏',face:'girl',
    lines:[
      '少女抬起頭，眼角仲帶住淚。「你唔好信佢。我已經死過兩次，死嗰刻明明好痛，但鏡頭一停，我又返返嚟。」',
      '佢望住你，忽然露出一個好勉強嘅笑容：「如果第三次真係要死一個人，你會唔會將我推出去？」',
      '放映室響起倒數聲。黎夏手指顫抖，仍然將一把鐵匙塞到你手掌。'
    ],
    choices:[
      {label:'答應保護黎夏，無論劇本點寫',hint:'黎夏信任・解鎖救人路線',to:'film_backstage',effect:{flags:['film_protect_xia'],bond:1,items:['放映室鐵匙'],journal:'你答應保護被困電影內的女主角黎夏。'}},
      {label:'問佢第二次死亡前見過乜',hint:'追查第四面牆',to:'film_projectionist',effect:{flags:['film_xia_memory'],sp:-4,journal:'黎夏曾看見攝影機後面站着另一個無名生還者。'}},
      {label:'承認自己冇把握，但唔會利用佢',hint:'坦白・保留合作',to:'film_backstage',effect:{flags:['film_honest_xia'],items:['放映室鐵匙']}}
    ]
  },
  film_projectionist:{
    id:'film_projectionist',world:'午夜放映廳',theme:'rift',title:'放映員的交易',speaker:'老廖',face:'clerk',
    lines:[
      '放映員慢慢轉身。佢手套上全部都係燒焦嘅膠片。「電影根本冇片尾。每次完場，都只係下一次重拍。」',
      '「你要搵嘅唔係最後一格，而係第一格。真正嘅出口藏喺開場嗰一下白光。」',
      '老廖將半格膠片擺喺你面前：「如果你肯替我熄咗放映機，我可以帶你離開。但戲入面啲人，會永久留低。」'
    ],
    choices:[
      {label:'相信佢嘅技術，但拒絕棄人離開',to:'film_backstage',effect:{flags:['film_first_frame_clue'],items:['第一格膠片'],journal:'真正出口藏在電影開場的第一格，不是片尾。'}},
      {label:'同意獨自走，叫佢即刻停機',hint:'快捷結局・犧牲黎夏',to:'film_ending',effect:{flags:['film_abandoned_cast'],sp:-15}},
      {label:'指出佢手套上嘅燒痕有問題',hint:'需要讀過劇本',to:'film_director',requires:'film_script_read',effect:{flags:['film_challenged_operator']}},
      {label:'偷偷記低機器型號，先去後台',to:'film_backstage',effect:{flags:['film_projector_id']}}
    ]
  },
  film_director:{
    id:'film_director',world:'午夜放映廳',theme:'rift',title:'第四面牆後面的導演',speaker:'老廖',face:'clerk',
    lines:[
      '老廖臉上嘅皮膚像舊底片咁逐格裂開。「你估我係放映員？我係每次重拍之後，被留下嚟記錄你選擇嘅人。」',
      '「每一部電影只會畀你一個劇本，但你偏偏成日想帶其他人出去。主神唔鍾意你咁做。」',
      '佢指住畫面外嘅座位：「第三次拍攝，主角必須講出一句冇寫入劇本嘅台詞。」'
    ],
    choices:[
      {label:'記低「劇本以外」嘅線索',to:'film_backstage',effect:{flags:['film_fourth_wall'],xp:20,journal:'電影世界監察者要求你講出劇本以外的一句台詞。'}},
      {label:'質疑主神有冇權替所有人安排結局',to:'film_backstage',effect:{flags:['film_rebellion'],sp:-8}}
    ]
  },
  film_backstage:{
    id:'film_backstage',world:'午夜放映廳',theme:'rift',title:'幕布後面',speaker:'旁白',face:'system',
    lines:[
      '你推開後台門。無數服裝掛喺空中，每一件都沾住唔同版本嘅血。角落裏面有一架倒轉播放嘅老舊攝影機。',
      '攝影機裏面，一個穿住你件衫嘅人正在對住鏡頭求救：「唔好相信你眼前嘅出口！」',
      '黎夏低聲問：「如果依家要你喺我同自己之間揀一個，你會點做？」佢眼神驚恐，但冇再避開你。'
    ],
    choices:[
      {label:'帶黎夏去放映室，尋找第一格',hint:'需要第一格線索・拯救路線',to:'film_edit',requires:'film_first_frame_clue',effect:{flags:['film_found_first_frame']}},
      {label:'透過四面牆線索修改電影台詞',hint:'已破解導演身份',to:'film_edit',requires:'film_fourth_wall',effect:{flags:['film_changed_script'],xp:35}},
      {label:'按照攝影機內嘅倒影去尋找出口',hint:'高風險・理智 -10',to:'film_bad_take',effect:{sp:-10,flags:['film_followed_double']}},
      {label:'堅持大家一齊逃，唔接受二選一',to:'film_edit',effect:{flags:['film_defied_choice']}}
    ]
  },
  film_bad_take:{
    id:'film_bad_take',world:'午夜放映廳',theme:'rift',title:'第二次死亡的回聲',speaker:'主神系統',face:'system',
    lines:[
      '【咔！】有人大嗌一聲「Cut」。你原本企住嘅位置突然消失，連同腳下嘅地板一齊被剪走。',
      '你跌返去戲院座位，掌心多咗一道真實傷口。銀幕上顯示「第三次拍攝即將開始」。',
      '有幾秒鐘，你甚至唔知道自己係觀眾，定係上一幕死咗嘅演員。'
    ],
    choices:[
      {label:'用痛楚確認自己仍然存在',hint:'生命 -10・取回清醒',to:'film_edit',effect:{hp:-10,flags:['film_survived_cut'],journal:'你抵抗電影的刪剪，從被剪掉的鏡頭中逃出。'}},
      {label:'放棄抵抗，讓電影帶你去片尾',hint:'理智 -18・壞結局',to:'film_ending',effect:{sp:-18,flags:['film_looped']}}
    ]
  },
  film_edit:{
    id:'film_edit',world:'午夜放映廳',theme:'rift',title:'第三次開拍',speaker:'旁白',face:'system',
    lines:[
      '攝影機亮起紅燈。銀幕變成一塊鏡，你看見自己站喺電影最後一場戲嘅舞台中央。',
      '導演聲音由四面八方傳嚟：「依照劇本，今晚一定要有人死。請你選擇一個犧牲者。」',
      '黎夏企喺你身旁，雙眼通紅。佢用力握住你手腕：「唔使一定係我……係咪？」'
    ],
    choices:[
      {label:'反轉膠片，將最後一格變回第一格',hint:'真結局・需要放映員情報',to:'film_final_frame',requires:'film_found_first_frame',effect:{flags:['film_true_route']}},
      {label:'講出未被寫入劇本嘅一句話',hint:'隱藏解謎・破解第四面牆',to:'film_final_frame',requires:'film_changed_script',effect:{flags:['film_true_route','film_fourth_wall_broken']}},
      {label:'將自己放喺鏡頭前，替黎夏擋下結局',hint:'生命 -22・黎夏會記得',to:'film_ending',requires:'film_protect_xia',effect:{hp:-22,flags:['film_xia_saved'],items:['刻有黎夏名字的票根']}},
      {label:'趁混亂一個人衝出消防通道',hint:'普通生還・角色關係受損',to:'film_ending',effect:{flags:['film_escaped_alone'],bond:-1}}
    ]
  },
  film_final_frame:{
    id:'film_final_frame',world:'午夜放映廳',theme:'rift',title:'銀幕以外的世界',speaker:'黎夏',face:'girl',
    lines:[
      '畫面開始倒轉。第一次拍攝嘅影像終於出現——你根本唔係被意外吸入電影，而係有人將你放進一套測試選擇嘅影片。',
      '放映機內嘅數據一張張燃燒。黎夏哭住笑咗：「原來我哋唔係唔可以離開，只係一直冇人敢改寫嗰句台詞。」',
      '你望住鏡頭，第一次知道電影真正嘅反派唔係劇中殺人兇手，而係喺鏡頭後面不斷重新拍攝嘅觀測者。'
    ],
    choices:[
      {label:'帶黎夏走出銀幕，讓所有人記得真相',to:'film_ending',effect:{flags:['film_free_all'],items:['未剪接的第一格'],xp:40,journal:'你打破第四面牆，解救被困在電影中的角色。'}},
      {label:'只銷毀放映記錄，令佢哋重新過生活',to:'film_ending',effect:{flags:['film_rewrote_end'],sp:8}}
    ]
  },
  film_ending:{
    id:'film_ending',world:'午夜放映廳',theme:'rift',title:'電影世界・最終字幕',speaker:'主神系統',face:'system',
    lines:[
      '舊戲院終於亮燈。你察覺銀幕上最後一行字幕唔係演員名單，而係你今次做過嘅每一個選擇。',
      '【電影世界任務完成。你有冇拯救演員，會影響之後世界對「被寫好的命運」嘅反應。】',
      '離開之前，你聽到攝影機響起最後一次「咔嚓」聲。鏡頭冇對住你，而係對住你背後嘅主神。'
    ],
    choices:[
      {label:'帶住黎夏嘅感謝返回主神空間',to:'hub_return',requires:'film_free_all',effect:{clearWorld:'午夜放映廳',points:125,xp:50,flags:['film_true_end'],journal:'電影世界真結局：所有演員不再受到劇本操控。'}},
      {label:'接受犧牲換來嘅生還，返回主神空間',to:'hub_return',requires:'film_xia_saved',effect:{clearWorld:'午夜放映廳',points:90,flags:['film_saved_end'],journal:'電影世界：你用自己生命的代價救下黎夏。'}},
      {label:'回到主神空間，記住呢場電影',to:'hub_return',effect:{clearWorld:'午夜放映廳',points:55,flags:['film_normal_end']}}
    ]
  },
  novel_arrival:{
    id:'novel_arrival',world:'霧中第七章',theme:'rift',title:'小說世界・消失的第七章',speaker:'旁白',face:'system',
    lines:[
      '【小說世界｜《霧中第七章》】你醒來時，正企喺一條濕漉漉嘅石板街。街上所有人都拿住書行路，但佢哋嘅嘴巴一張一合，發出嘅卻係紙張翻頁聲。',
      '一隻白鴿飛過，你發現佢嘅影子唔係鳥，而係一句句不停被改寫嘅文字。',
      '路牌寫住：「故事總共有六章。任何人提及第七章，都必須替作者補上結局。」',
      '【主神任務】尋找失蹤的第七章，保住故事主角嘅生命，或者改寫佢嘅命運。'
    ],
    choices:[
      {label:'前往圖書館查閱原稿',hint:'調查世界規則',to:'novel_library'},
      {label:'追住白鴿尋找寫字嘅人',hint:'角色故事線',to:'novel_author'},
      {label:'停低聽街角少女講故事',hint:'人物對話・主角線索',to:'novel_heroine'}
    ]
  },
  novel_library:{
    id:'novel_library',world:'霧中第七章',theme:'rift',title:'沒有第七章的圖書館',speaker:'館長',face:'clerk',
    lines:[
      '圖書館每本書都冇最後一頁。館長鼻樑上架住一副沒有鏡片嘅眼鏡：「故事去到第六章就應該完。所有超出原稿嘅人物，都屬於錯誤。」',
      '你偷偷翻開一本書，發現「主角會喺今晚午夜消失」嘅句子旁邊有人寫咗細字：「如果佢肯相信陌生人，就會活下來。」',
      '你想起零號月台嘅經歷。你自己何嘗唔係一個冇名字、被原本故事刪除嘅人？'
    ],
    choices:[
      {label:'抄低書邊嘅隱藏註解',to:'novel_heroine',effect:{flags:['novel_margins'],items:['第七章手稿碎頁'],journal:'小說世界原稿旁註：主角相信陌生人就可能生還。'}},
      {label:'問館長點解書一定要停喺第六章',to:'novel_librarian',effect:{flags:['novel_asked_end']}},
      {label:'偷走一本未完成嘅書',hint:'理智 -7・可能改變故事',to:'novel_crossout',effect:{sp:-7,flags:['novel_stole_book']}}
    ]
  },
  novel_librarian:{
    id:'novel_librarian',world:'霧中第七章',theme:'rift',title:'主角被刪除的原因',speaker:'館長',face:'clerk',
    lines:[
      '館長沉默片刻，忽然露出悲傷嘅神情。「因為第七章嘅結局，唔係作者親手寫嘅。」',
      '「有個讀者見到主角就快死，偷偷加咗一句話。從此每個讀者都想修改佢嘅故事，故事本身就開始崩潰。」',
      '「有時善意都會害死人。你係咪仲要做第二個讀者？」'
    ],
    choices:[
      {label:'先證明原稿可以同角色意願共存',hint:'理智 -5・情報',to:'novel_heroine',effect:{sp:-5,flags:['novel_editor_truth'],journal:'小說世界不是單純修改文字：違反角色意願會令故事崩潰。'}},
      {label:'相信館長，嘗試接受第六章結局',to:'novel_crossout',effect:{flags:['novel_fate_accept']}}
    ]
  },
  novel_author:{
    id:'novel_author',world:'霧中第七章',theme:'rift',title:'失蹤作者的影子',speaker:'旁白',face:'system',
    lines:[
      '白鴿停喺一間關咗門嘅出版社窗邊。玻璃映住一個低頭寫字嘅人，但室內根本冇人。',
      '一行字浮現喺玻璃：「如果你讀到這段話，請替我問她——她真的願意被寫成悲劇嗎？」',
      '你聽到樓下傳來少女嘅聲音。原來作者留下嘅唔係命令，而係一個未被回答嘅問題。'
    ],
    choices:[
      {label:'帶住作者嘅問題去搵女主角',to:'novel_heroine',effect:{flags:['novel_author_question'],items:['作者最後的提問'],journal:'原作者想知道女主角是否願意接受悲劇。'}},
      {label:'將玻璃上嘅字擦走',to:'novel_crossout',effect:{flags:['novel_erased_author'],sp:-7}}
    ]
  },
  novel_heroine:{
    id:'novel_heroine',world:'霧中第七章',theme:'rift',title:'不知道自己是主角的女孩',speaker:'紀青',face:'girl',
    lines:[
      '少女坐喺咖啡店窗邊，雙手攬住杯已經涼晒嘅紅茶。佢笑得好淡：「大家都話我今晚會死，因為故事係咁寫。」',
      '「但我連聽日想食乜都仲未諗好。點解一個從未見過我嘅作者，可以決定我幾時死？」',
      '紀青望住你，雙眼第一次有咗希望：「你唔係書入面嘅人，係咪？如果真係咁，你可唔可以聽吓我自己想揀嘅結局？」'
    ],
    choices:[
      {label:'認真聽紀青講完佢嘅願望',hint:'信任 +1・解鎖真結局',to:'novel_confession',effect:{flags:['novel_heard_her'],bond:1}},
      {label:'直接話佢只要逃跑就得',hint:'高風險捷徑',to:'novel_crossout',effect:{flags:['novel_rushed_escape']}},
      {label:'攞出作者留下嘅問題畀佢睇',hint:'需要作者情報',to:'novel_confession',requires:'novel_author_question',effect:{flags:['novel_writer_reconciled']}}
    ]
  },
  novel_confession:{
    id:'novel_confession',world:'霧中第七章',theme:'rift',title:'女主角自己的願望',speaker:'紀青',face:'girl',
    lines:[
      '紀青低聲講：「其實我唔係最驚死。我最驚嘅係，就算我努力過，大家都只會記得我係一個注定會死嘅女主角。」',
      '佢眼角慢慢泛紅，但語氣非常堅定：「如果一定要有第七章，我希望由我自己寫第一句。」',
      '你發現佢攞住嘅書，最後一頁開始由空白變成有微弱光芒。'
    ],
    choices:[
      {label:'將筆交畀紀青，讓佢自己決定',to:'novel_rewrite',effect:{flags:['novel_gave_pen'],items:['無字鋼筆'],journal:'紀青決定親手寫出自己的第七章。'}},
      {label:'由你代寫一句能令佢生存嘅句子',to:'novel_crossout',effect:{flags:['novel_override_heroine']}},
      {label:'先同館長商量改寫規則',to:'novel_rewrite',requires:'novel_margins',effect:{flags:['novel_coauthor']}}
    ]
  },
  novel_crossout:{
    id:'novel_crossout',world:'霧中第七章',theme:'rift',title:'被塗掉的文字',speaker:'旁白',face:'system',
    lines:[
      '你想直接改變故事，但墨水一滴落紙，街上所有人嘅臉就變成空白。每一個字都好似喺抽走某個人嘅記憶。',
      '圖書館高處傳來巨大嘅翻頁聲，系統突然響起：「違反故事完整性。讀者即將被刪除。」',
      '你剩低幾秒鐘決定——要回收自己嘅改動，定係接受錯誤帶來嘅代價。'
    ],
    choices:[
      {label:'將修改權交回故事內嘅人物',hint:'理智 -10・返回主線',to:'novel_rewrite',effect:{sp:-10,flags:['novel_retracted']}},
      {label:'繼續強行改寫劇情',hint:'生命 -20・失控結局',to:'novel_ending',effect:{hp:-20,flags:['novel_forced_end']}}
    ]
  },
  novel_rewrite:{
    id:'novel_rewrite',world:'霧中第七章',theme:'rift',title:'真正的第七章',speaker:'旁白',face:'system',
    lines:[
      '鐘聲響起，午夜終於到咗。小說入面原本寫好嘅死亡場景逐字浮現在半空。',
      '紀青攞起筆，停喺第一句之前。你第一次見到一個故事角色有機會否定自己原本嘅結局。',
      '圖書館館長從後面追過來：「你哋知唔知自己咁做會令所有書頁散落？」'
    ],
    choices:[
      {label:'畀紀青自己寫出第七章',hint:'真結局・需尊重角色意願',to:'novel_ending',requires:'novel_gave_pen',effect:{flags:['novel_true_end_ready'],xp:40,items:['親筆寫下的第七章'],journal:'紀青成功自己決定生命故事的結局。'}},
      {label:'與紀青一齊構思，但由佢落筆',hint:'合作路線',to:'novel_ending',requires:'novel_coauthor',effect:{flags:['novel_true_end_ready'],xp:30}},
      {label:'犧牲手稿保全小說世界',hint:'理智 -8・平衡結局',to:'novel_ending',effect:{sp:-8,flags:['novel_saved_world']}},
      {label:'唔再改動，讓故事照舊發生',hint:'普通結局',to:'novel_ending',effect:{flags:['novel_normal_end']}}
    ]
  },
  novel_ending:{
    id:'novel_ending',world:'霧中第七章',theme:'rift',title:'小說世界・讀者結算',speaker:'主神系統',face:'system',
    lines:[
      '書頁像雪咁由天上飄落，覆蓋咗成條石板街。原本應該停喺第六章嘅小說，終於出現第七章嘅頁碼。',
      '你聽到有個聲音喺耳邊問：「究竟係作者創造人物，定係人物都可以改寫作者？」',
      '【任務完成。你對「自由意志」嘅選擇已記錄，會影響以後進入電影與小說世界嘅選項。】'
    ],
    choices:[
      {label:'保留紀青寫下嘅第七章返回中轉站',to:'hub_return',requires:'novel_true_end_ready',effect:{clearWorld:'霧中第七章',points:115,xp:50,flags:['novel_true_end'],journal:'小說世界真結局：紀青自己寫出命運。'}},
      {label:'保護小說世界，讓故事繼續流傳',to:'hub_return',requires:'novel_saved_world',effect:{clearWorld:'霧中第七章',points:85,flags:['novel_world_end']}},
      {label:'帶走故事遺留下來的空白頁',to:'hub_return',effect:{clearWorld:'霧中第七章',points:55,flags:['novel_normal_end']}}
    ]
  },
  lost_direct_confront:{
    id:'lost_direct_confront',world:'失物管理處',theme:'archive',title:'巨剪與沒有姓名的人',speaker:'失物管理員',face:'clerk',
    lines:[
      '管理員嘅巨剪向你頭頂劈落。你反射性舉起鏡面碎片，一道冰冷光線劃開空氣。呢唔係一場公平嘅戰鬥——你必須喺幾秒之內搵出佢嘅規則漏洞。',
      '「登記在案嘅失物，永遠走唔出管理處。」管理員狂笑，但你察覺每當佢講「失物」，鏡面就照出另一個冇名字嘅身影。',
      '你可以用真相證明自己係活人，或者冒險用鏡面硬擋落去。'
    ],
    choices:[
      {label:'用守則指出活人不能算失物',hint:'規則破解・減少代價',to:'lost_after_battle',requires:'lost_rules',effect:{sp:-3,flags:['clerk_defeated','clerk_outwitted'],points:25,journal:'你用守則破解巨剪管理員的規則，未有正式開戰。'}},
      {label:'用鏡面折射剪刀，冒死突圍',hint:'生命 -17・理智 -9',to:'lost_after_battle',effect:{hp:-17,sp:-9,flags:['clerk_defeated','clerk_mirror_escape'],journal:'你用鏡面碎片逃脫了管理員的襲擊。'}},
      {label:'反過來同管理員交換你嘅「失物身份」',hint:'理智 -16・暗線',to:'lost_ending',effect:{sp:-16,flags:['clerk_bargained'],items:['空白領取證']}}
    ]
  },
  rift_story_trial:{
    id:'rift_story_trial',world:'未知世界',theme:'rift',title:'規則裂隙・不需要拔劍的對抗',speaker:'旁白',face:'system',
    lines:[
      '守門者由霧入面走出嚟。佢冇武器，只係將你上一個世界做過嘅選擇，一項項念出來。',
      '「你以為你能夠逃避代價？每一次穿越，都會有一個世界記住你。」守門者將兩道門擺喺你面前。',
      '一扇門寫住「犧牲力量」，另一扇寫住「承認恐懼」。呢一刻，用劍根本解決唔到問題。'
    ],
    choices:[
      {label:'坦白承認自己仍然會恐懼',to:'rift_exit',effect:{sp:-6,points:25,flags:['rift_admitted_fear'],journal:'你承認恐懼，避開了裂隙守門者的試煉。'}},
      {label:'犧牲部分生命，換取安全通道',hint:'生命 -14',to:'rift_exit',effect:{hp:-14,points:35,flags:['rift_paid_life']}},
      {label:'將鏡面碎片對準守門者的倒影',hint:'鏡域天賦專屬',to:'rift_exit',requiresTalent:'mirror',effect:{sp:-5,points:50,xp:25,flags:['rift_mirror_solved']}}
    ]
  }
}
